### ISSUE TITLE
cannot support Alpha-Channel video?

### ISSUE THREAD

**Issue by coollofty** [Raveler/ffmpeg-cpp#25]
I tested a video file with .webm format, and you can see its translucent effect in chrome. After decoding with ffmpeg-cpp, cv::Mat does have 4 channels, but the value of the alpha channel is all 255 , Is my operation incorrect?

**Comment by TechnikEmpire** [comment]
I'm a casual observer but typically in opencv you'll want to be scaling those values with 1.0/255 pixel wise and multiply your color channels by that intensity. Google alpha blending in opencv.

**Comment by coollofty** [comment]
> I'm a casual observer but typically in opencv you'll want to be scaling those values with 1.0/255 pixel wise and multiply your color channels by that intensity. Google alpha blending in opencv.

It seems that this is not the case, ffmpeg's vp9 decoder does not support alpha channel ....
